### ISSUE TITLE
Page Numbers wrong for Tech Reports with long ToC

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#151]
**Describe the bug**

Page numbers for front matter are wrong  when the table of contents is long. This affects the citation on the colophon page, and the page numbers for the English and French abstracts. 

**To Reproduce**

A minimal example is [here](https://www.dropbox.com/sh/ydpkac8jud47l1i/AABIyq-mBRbooZh_biTHB3bLa?dl=0). 

**Observed behavior**

The front matter has *vii* pages, but the citation on the colophon page shows *v*. 

English and French abstracts are on pages *vi* and *vii*, but the ToC shows *iv* and *v*

**Desktop**
 - Operating system: Windows
 - R version: R version 4.0.2 (2020-06-22)
 - csasdown version: 0.0.8

**Comment by seananderson** [comment]
It looks like this is just because `tinytex::latexmk()` isn't running `pdflatex` enough times. This issue goes right back to R Markdown if not pandoc and I see references to it in the bookdown issues. I'm not sure there is an elegant solution to this besides figuring out the bug up the chain, but I added a helper function (`csasdown::run_pdflatex()`) that will copy the .tex file to the main folder, rerun latexmk, run extra pdflatex (default 1 extra run), and copy the PDF back into the _book folder. Run this after the initial knitting. If this turns out to be a common problem, perhaps we should write out own wrapper for `bookdown::render_book()` that can do this based on an argument... or you could do that for your own use.

https://github.com/pbs-assess/csasdown/blob/master/R/run_pdflatex.R

**Comment by cgrandin** [comment]
I just ran this with your changes @seananderson and the problem remains (I'm on Windows). The TOC says the ABSTRACT is on page iv but it is actually on vi. Is this a Windows issue? **I wrote this at the same time you were writing your response above**

**Comment by seananderson** [comment]
Last comment was posted simultaneously with my explanation. The `csasdown::run_pdflatex()` command should solve this problem. @SOLV-Code let me know if it does not.

**Comment by SOLV-Code** [comment]
re-installed the package and ran ```csasdown::run_pdflatex()``` twice, but still getting the same problem in existing reports.
Will try with a brand new sample report, built from scratch.

**Comment by seananderson** [comment]
Even `csasdown::run_pdflatex(2)` or `csasdown::run_pdflatex(3)`? Does it work on the minimal example you provided? I thought it worked there for me.

**Comment by SOLV-Code** [comment]
Sorry, still not working...

I uninstalled *csasdown*, re-installed it, updated all the dependencies (rmarkdown from 2.3 to 2.4), generated a new tech report folder, and only moved over the intro to appendix Rmd files from the earlier minimal example, then knitted and ran ```csasdown::run_pdflatex(3)```.

Any ideas for other things I could try?

**Comment by seananderson** [comment]
Sorry about that. I was testing on the command line and didn't realize the default in tinytex was that `clean = TRUE` so the various auxiliary files were never building up across runs. Should be fixed now in your minimal example.

**Comment by SOLV-Code** [comment]
Fixed! Thank you!  And more generally thank you for creating and maintaining this package. It has really streamlined the workflow...
